spring:
#  datasource:
#    url: jdbc:h2:./db_test;MODE=MySQL
  datasource:
    # 데이터베이스 연결 URL
    url: jdbc:mariadb://localhost:3306/qnaService_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul